services:
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - mysql5:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: true
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: clients
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

    back:
        depends_on:
          db:
            condition: service_healthy
        build:
            context: .
        ports:
            - "4000:4000"

volumes:
    mysql5:
